Fix react router plugin
oedotme/generouted pull request #47
Opened 2023-02-11 16:46 UTC by brotherko

This PR is intended to fix two problems:
1. The plugin previously encountered difficulties in detecting when the loader/action function was defined using Typescript.
2. The arguments from react-router were unable to be correctly passed to the function using func.apply.

As this is my first time submitting a pull request on GitHub :) kindly advise me if there is anything I can improve on thx

2023-02-12 16:01 UTC, oedotme requested changes
Hey @brotherko, Awesome! I'm glad you made your first GitHub contribution on this project!

It looks good overall and you addressed the issues :rocket: I've left a few comments for type errors and another suggestion for export names pattern constraints.

2023-02-13 01:31 UTC, brotherko commented on plugins/react-router/src/template.ts
> +const router = createBrowserRouter([{ element: <App children={<Outlet />} />, children: routes }])
What kind of type error are you referring to here?

2023-02-13 14:33 UTC, oedotme commented on plugins/react-router/src/template.ts
> +const router = createBrowserRouter([{ element: <App children={<Outlet />} />, children: routes }])
For example if the exported `App` component from `pages/_app.tsx` doesn't accept a `children` prop it would throw an error.

2023-02-13 14:34 UTC, oedotme commented
@brotherko Thanks again for fixing this! I'll merge and release it shortly.

2023-02-13 15:03 UTC, merged

2023-02-13 15:13 UTC, oedotme commented
Released at https://github.com/oedotme/generouted/releases/tag/v1.7.7